"""Regenerate lib/quorum_consensus.py from the contract.

    python scripts/lift.py

The lifted module claims to be the agreement rules "as the contract runs them".
Maintaining it by hand makes that claim false the first time somebody edits one
side, and a copied rule that no deployed contract uses is worse than no copy at
all -- it is a rule with a provenance it has not earned.

So the copy is generated, and tests/test_logic.py::TestLibParity compares the
two parsed trees function by function. Editing the contract and forgetting to
run this turns into a failing test rather than into a quiet lie.
"""

import ast
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
CONTRACT = ROOT / "contracts" / "quorum.py"
OUT = ROOT / "lib" / "quorum_consensus.py"

CONSTANTS = ['UNSTATED', 'ESTABLISHED', 'CONTESTED', 'INSUFFICIENT', 'VERDICTS', 'MAX_SOURCES', 'MIN_SOURCE', 'MAX_SOURCE', 'MIN_QUESTION', 'MAX_QUESTION', 'MAX_ANSWERS', 'MAX_ANSWER', 'ANSWER_ALPHABET', 'MAX_DELEGATES', 'MAX_DELEGATE_ROWS', 'MAX_SOURCE_ROWS', 'MAX_ROWS_PER_ACCOUNT', 'MAX_REASON']

FUNCTIONS = ['looks_like_address', 'clean_text', 'clean_line', 'split_answers', 'normalise_token', 'parse_vector', 'reconcile', 'tally', 'structurally_sound', 'quorum_agrees', 'sanitise_reason', 'fence', 'number', 'build_prompt']

HEADER = '''# quorum_consensus.py - the agreement rules, lifted out to be copied.
#
# GENERATED by scripts/lift.py from contracts/quorum.py. Do not edit by hand:
# tests/test_logic.py compares the two parsed trees function by function, so an
# edit here fails the suite rather than quietly claiming a provenance it does
# not have.
#
# GenLayer contracts run as ONE Python file inside the GenVM. There is no pip
# install and no cross-file import at deploy time, so this is not a module you
# import: it is a curated block. contracts/quorum.py already inlines these
# helpers. This file exists so the rules can be read and lifted into another
# project without reading a whole contract first.
#
# Everything here is pure. No storage, no network, no model. That is the point:
# these are the functions a validator runs to decide whether two nodes agreed,
# and a function that decides agreement must be deterministic or it decides
# nothing at all.
#
# quorum_agrees is SYMMETRIC: agrees(a, b) == agrees(b, a).
#
# Two ideas are worth lifting. reconcile() folds two presentation orders into
# one vector and records any source the orders read differently as `unstated`,
# exactly as if it had said nothing, so position bias lands on the conservative
# value and nothing records that the orders disagreed. tally() is the quorum
# rule: an answer is established only at or above the threshold with NO other
# answer present, so one dissent is contested, never outvoted.

# ---------------------------------------------------------------------------
# Deterministic helpers. Pure, module level, unit tested in tests/test_logic.py
# ---------------------------------------------------------------------------

'''


def main():
    src = CONTRACT.read_text(encoding="utf-8")
    tree = ast.parse(src)
    lines = src.splitlines(keepends=True)

    def segment(node):
        return "".join(lines[node.lineno - 1:node.end_lineno]).rstrip("\n")

    parts = []
    for name in CONSTANTS:
        for n in tree.body:
            if isinstance(n, ast.Assign) and any(
                    isinstance(t, ast.Name) and t.id == name for t in n.targets):
                parts.append(segment(n))
                break
        else:
            raise SystemExit(f"the contract no longer defines {name}")

    fns = []
    for name in FUNCTIONS:
        for n in tree.body:
            if isinstance(n, ast.FunctionDef) and n.name == name:
                fns.append(segment(n))
                break
        else:
            raise SystemExit(f"the contract no longer defines {name}()")

    OUT.write_text(
        HEADER + "\n".join(parts) + "\n\n\n" + "\n\n\n".join(fns) + "\n",
        encoding="utf-8",
    )
    print(f"  {OUT.relative_to(ROOT)}: {len(CONSTANTS)} constants, {len(FUNCTIONS)} functions")


if __name__ == "__main__":
    main()
